import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "katex/dist/katex.min.css";
import "github-markdown-css/github-markdown-light.css";
import Footer from "@/components/molecules/footer";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mansur Nurmukhambetov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col gap-2")}>
        <nav />
        <main className="mx-auto w-full max-w-3xl max-md:px-4 max-md:max-w-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
