# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Github Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Delete .obsidian folder
        run: rm -rf .obsidian
      - name: Move files to public folder
        run: | 
          mkdir public 
          mkdir public/attachments
          find . -name "*.md" -exec mv {} public/ \;
          find . -name "attachments/*" -exec mv {} public/attachments \;
      - name: Clone the website builder
        run: |
          git clone https://github.com/nomomon/personal-website-builder pwb
          rm -rf pwb/.git
          mv pwb/* . && rm -rf pwb
      - name: Debug view
        run: |
          ls
          ls public
          ls public/attachments
      - name: Install packages
        run: npm ci
      - name: Make build
        run: npm run export
      - name: Add .nojekyll file
        run: touch out/.nojekyll
      - name: Add github pages config
        run: git config --global safe.directory '*'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: always()
        with:
          branch: gh-pages
          folder: out
