# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Github Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Delete .obsidian folder
        run: rm -rf .obsidian
      - name: Create public folder and move files there
        run: mkdir public && find . -maxdepth 1 ! -name public -exec mv {} public/ \;
      - name: Clone the website builder
        run: git clone https://github.com/nomomon/personal-website-builder
      - name: Install packages
        run: npm ci
      - name: Make build
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
